In [1]:
import numpy as np
import tensorflow as tf
load_model = tf.keras.models.load_model
import pandas as pd
import joblib as jbl

In [2]:
def out_matrix(X, n_hidden, centroids, sigma_mat):
        out_mat = np.zeros((X.shape[0], n_hidden))
        for i in range(len(X)):
            for j in range(n_hidden):
                numerator = -np.square(X[i] - centroids[j]).sum()
                denominator = 2*(np.square(sigma_mat[j]))
                out_mat[i][j] = np.exp(numerator/denominator)
        return out_mat

In [53]:
def scale(x, x_min, x_max):
    return np.array([[(x[i] - x_min[i]) / (x_max[i] - x_min[i]) for i in range(len(x))]])

# Temperature / Humidity

In [3]:
temp_data = jbl.load('temperature_Metadata_N_12_P_11_bs_32.jbl')
temp_data.keys()

dict_keys(['neurons', 'centers', 'sigma', 'batch_size', 'lr', 'loss_fn'])

In [4]:
all_temp_data = jbl.load('/Users/prabhukiran/Desktop/complete_sample_predictions/clean_exported_datasets/all_temp_data.joblib')
all_temp_data.keys()

dict_keys(['modified_data_orig', 'temp_x_scalar', 'temp_y_scalar', 'temp_x_data_scaled', 'temp_y_data_scaled', 'X_train_temp', 'X_test_temp', 'y_train_temp', 'y_test_temp', 'metadata'])

In [114]:
all_humidity_data = jbl.load('/Users/prabhukiran/Desktop/complete_sample_predictions/clean_exported_datasets/all_humidity_data.joblib')
all_humidity_data.keys()

dict_keys(['modified_data_orig', 'humidity_x_scalar', 'humidity_y_scalar', 'humidity_x_data_scaled', 'humidity_y_data_scaled', 'X_train_humidity', 'X_test_humidity', 'y_train_humidity', 'y_test_humidity', 'metadata'])

In [158]:
all_load_data = jbl.load('/Users/prabhukiran/Desktop/complete_sample_predictions/clean_exported_datasets/all_original_load_data.joblib')
all_load_data.keys()

dict_keys(['load_data', 'load_X_scaler', 'load_y_scaler', 'load_X_data_scaled', 'load_y_data_scaled', 'load_X_train', 'load_X_test', 'load_y_train', 'load_y_test', 'metadata'])

In [182]:
all_compressed_data = jbl.load('/Users/prabhukiran/Desktop/complete_sample_predictions/clean_exported_datasets/compressed_data_info.joblib')
all_compressed_data.keys()

dict_keys(['compressed_X_train_data', 'compressed_X_test_data', 'load_y_train', 'load_y_test'])

In [163]:
load_df =all_load_data['load_data']
load_df

T-1          T-2          T-3          T-4         T-24  \
0     2083.646729   455.976231   515.451392   654.226767  2260.056104   
1     2062.165835  2083.646729   455.976231   515.451392  2260.056104   
2     2062.165835  2062.165835  2083.646729   455.976231  2260.056104   
3     2062.165835  2062.165835  2062.165835  2083.646729  2555.415800   
4     2294.620910  2062.165835  2062.165835  2062.165835  2845.399210   
...           ...          ...          ...          ...          ...   
8659  1240.667993  1011.621595   847.076768  4727.043782  1160.855092   
8660  1221.580794  1240.667993  1011.621595   847.076768  1011.067338   
8661  1173.204615  1221.580794  1240.667993  1011.621595   898.726523   
8662  1078.591339  1173.204615  1221.580794  1240.667993  2023.111553   
8663   908.287443  1078.591339  1173.204615  1221.580794  2023.111553   

             T-48         T-72         T-96  DAY  SEASON  TEMP  HUMIDITY  \
0     2236.756556  1828.915749  1967.388015  0.0     1.0  66.0      90.0   
1     2236.756556  1828.915749  1967.388015  0.0     1.0  66.0      90.0   
2     2354.480586  1828.915749  1967.388015  0.0     1.0  66.0      90.0   
3     2511.445958  1892.265507  2442.607331  0.0     1.0  80.0      40.0   
4     2805.756031  2532.344883  2756.205522  0.0     1.0  80.0      40.0   
...           ...          ...          ...  ...     ...   ...       ...   
8659  1154.281959  1116.436649  1097.513994  0.0     1.0  67.0      92.0   
8660   965.055409  1021.823374   965.055409  0.0     1.0  67.0      92.0   
8661   851.519478   946.132754   919.147402  0.0     1.0  65.0      94.0   
8662  2668.094365   878.011195   825.356851  0.0     1.0  65.0      94.0   
8663  2724.862330  2462.248787   825.356851  0.0     1.0  65.0      94.0   

                T  
0     2062.165835  
1     2062.165835  
2     2062.165835  
3     2294.620910  
4     2710.645657  
...           ...  
8659  1221.580794  
8660  1173.204615  
8661  1078.591339  
8662   908.287443  
8663   839.836796  

[8664 rows x 13 columns]

In [5]:
temp_df = all_temp_data['modified_data_orig']
temp_df

T-1  T-24   H-1  H-24  Season     T
0     62.0  65.0  89.0  90.0     1.0  65.0
1     65.0  65.0  90.0  90.0     1.0  65.0
2     65.0  65.0  90.0  90.0     1.0  65.0
3     65.0  78.0  90.0  49.0     1.0  78.0
4     78.0  78.0  48.0  49.0     1.0  78.0
...    ...   ...   ...   ...     ...   ...
8731  67.0  69.0  92.0  88.0     1.0  67.0
8732  67.0  69.0  92.0  88.0     1.0  67.0
8733  67.0  65.0  92.0  94.0     1.0  65.0
8734  65.0  65.0  94.0  94.0     1.0  65.0
8735  65.0  65.0  94.0  94.0     1.0  65.0

[8736 rows x 6 columns]

In [61]:
temp_y_scaler = all_temp_data['temp_y_scalar']

In [115]:
humidity_y_scaler = all_humidity_data['humidity_y_scalar']
humidity_y_scaler.data_max_, humidity_y_scaler.data_min_

(array([102.]), array([14.]))

In [116]:
humidity_x_scaler = all_humidity_data['humidity_x_scalar']

In [117]:
humidity_x_scaler.data_max_, humidity_x_scaler.data_min_

(array([108., 108., 102., 102.,   2.]), array([50., 50., 14., 14.,  0.]))

In [62]:
temp_y_scaler.data_max_, temp_y_scaler.data_min_

(array([108.]), array([50.]))

In [159]:
load_x_scaler = all_load_data['load_X_scaler']
load_y_scaler = all_load_data['load_y_scaler']

In [6]:
temp_max = temp_df.max().to_numpy()
temp_max

array([108., 108., 102., 102.,   2., 108.])

In [7]:
all_temp_data['temp_x_data_scaled']

array([[0.20689655, 0.25862069, 0.85227273, 0.86363636, 0.5       ],
       [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
       [0.25862069, 0.25862069, 0.86363636, 0.86363636, 0.5       ],
       ...,
       [0.29310345, 0.25862069, 0.88636364, 0.90909091, 0.5       ],
       [0.25862069, 0.25862069, 0.90909091, 0.90909091, 0.5       ],
       [0.25862069, 0.25862069, 0.90909091, 0.90909091, 0.5       ]])

In [8]:
temp_X_scaler = all_temp_data['temp_x_scalar']
temp_X_scaler

MinMaxScaler()

In [9]:
temp_X_scaler.data_min_, temp_X_scaler.data_max_

(array([50., 50., 14., 14.,  0.]), array([108., 108., 102., 102.,   2.]))

In [10]:
temp_max = temp_X_scaler.data_max_
temp_min = temp_X_scaler.data_min_

In [11]:
# def scale(x, x_max, x_min):
#     X_scaled = np.zeros((x.shape[0], x.shape[1]))
#     for i in range(x.shape[1]):
#         X_scaled[:, i] = (x[:, i] - x_min[i])/(x_max[i] - x_min[i])
#     return X_scaled

In [103]:
sample_temp_data = temp_df.sample(1)

In [164]:
sample_load_data = load_df.sample(1)
sample_load_data

T-1          T-2          T-3          T-4         T-24  \
7233  2022.134677  2096.377303  2096.377303  1907.514483  2171.596805   

             T-48         T-72         T-96  DAY  SEASON  TEMP  HUMIDITY  \
7233  2505.649131  2002.233413  2321.710184  0.0     1.0  80.0      62.0   

                T  
7233  1907.514483

In [104]:
sample_temp_data = sample_temp_data.values
sample_temp_data

array([[84., 84., 77., 86.,  0., 84.]])

In [165]:
sample_load_data = sample_load_data.values
sample_load_data

array([[2.02213468e+03, 2.09637730e+03, 2.09637730e+03, 1.90751448e+03,
        2.17159681e+03, 2.50564913e+03, 2.00223341e+03, 2.32171018e+03,
        0.00000000e+00, 1.00000000e+00, 8.00000000e+01, 6.20000000e+01,
        1.90751448e+03]])

In [105]:
sample_temp_data.shape

(1, 6)

In [166]:
sample_load_data.shape

(1, 13)

In [106]:
temp_X, temp_y = sample_temp_data[0][:-1], sample_temp_data[0][-1]
temp_X, temp_y

(array([84., 84., 77., 86.,  0.]), 84.0)

In [167]:
load_X, load_y = sample_load_data[0][:-1], sample_load_data[0][-1]
load_X, load_y

(array([2.02213468e+03, 2.09637730e+03, 2.09637730e+03, 1.90751448e+03,
        2.17159681e+03, 2.50564913e+03, 2.00223341e+03, 2.32171018e+03,
        0.00000000e+00, 1.00000000e+00, 8.00000000e+01, 6.20000000e+01]),
 1907.5144825788343)

In [16]:
temp_X

array([82., 81., 84., 89.,  0.])

In [107]:
temp_X, temp_X.shape

(array([84., 84., 77., 86.,  0.]), (5,))

In [18]:
temp_min, temp_max

(array([50., 50., 14., 14.,  0.]), array([108., 108., 102., 102.,   2.]))

In [19]:
(70. - 50) / (108 - 50)

0.3448275862068966

In [54]:
temp_X_scaled = scale(temp_X, temp_min, temp_max)

In [57]:
temp_X_scaled

array([[0.55172414, 0.53448276, 0.79545455, 0.85227273, 0.        ]])

In [26]:
print(temp_X)
print(temp_max)
print(temp_min)

[82. 81. 84. 89.  0.]
[108. 108. 102. 102.   2.]
[50. 50. 14. 14.  0.]


In [48]:
temp_X

array([82., 81., 84., 89.,  0.])

In [27]:
(82 - 108) / (108 - 50)

-0.4482758620689655

In [47]:
temp_X_scaler.transform(temp_X.reshape(1, -1))

/opt/miniconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.55172414, 0.53448276, 0.79545455, 0.85227273, 0.        ]])

In [43]:
temp_df.drop('T', axis=1).max().to_numpy(), temp_df.drop('T', axis=1).min().to_numpy()

(array([108., 108., 102., 102.,   2.]), array([50., 50., 14., 14.,  0.]))

In [49]:
(82 - 50) / (108 - 50)

0.5517241379310345

In [58]:
temp_RBF = jbl.load('temperature_Metadata_N_12_P_11_bs_32.jbl')
temp_RBF.keys()

dict_keys(['neurons', 'centers', 'sigma', 'batch_size', 'lr', 'loss_fn'])

In [118]:
humidity_RBF = jbl.load("humidity_Metadata_N_12_P_10_bs_128.jbl")
humidity_RBF.keys()

dict_keys(['neurons', 'centers', 'sigma', 'batch_size', 'lr', 'loss_fn'])

In [154]:
load_RBF = jbl.load('load_Metadata_N_19_P_12_bs_32.jbl')
load_RBF.keys()

dict_keys(['neurons', 'centers', 'sigma', 'batch_size', 'lr', 'loss_fn'])

In [77]:
temp_ann = tf.keras.models.load_model('temperature_RBF_ANN_model_bs_32_N_12_P_11.h5', compile=False)
temp_ann.get_weights()[0]

array([[-0.24627198],
       [-1.5727873 ],
       [ 1.0005498 ],
       [ 0.4618668 ],
       [ 1.2107803 ],
       [-1.1432909 ],
       [-0.5108953 ],
       [ 1.0042504 ],
       [-0.4536422 ],
       [ 1.0440261 ],
       [-0.2035781 ],
       [-0.00465495]], dtype=float32)

In [122]:
humidity_ann = tf.keras.models.load_model('humidity_RBF_ANN_model_bs_128_N_12_P_10.h5', compile=False)
humidity_ann.get_weights()

[array([[-0.30151144],
        [-0.35921514],
        [ 0.87231857],
        [-0.34067824],
        [ 0.05569633],
        [-0.07151955],
        [ 0.7730289 ],
        [ 1.0468769 ],
        [ 0.21688782],
        [ 0.6648987 ],
        [-0.7167899 ],
        [-1.0972459 ]], dtype=float32),
 array([0.14118692], dtype=float32)]

In [156]:
load_ann = load_model('load_RBF_ANN_model_bs_32_N_19_P_12.h5', compile=False)
load_ann.get_weights()

[array([[ 1.6952595 ],
        [ 0.5129921 ],
        [-0.6252557 ],
        [ 0.5787313 ],
        [-0.7234435 ],
        [ 0.4818933 ],
        [ 0.9326393 ],
        [-0.60815436],
        [-0.38618377],
        [ 0.29487938],
        [-0.35583895],
        [-1.1777999 ],
        [-0.14523646],
        [-1.1294508 ],
        [-0.3709881 ],
        [-0.02318509],
        [-0.12705478],
        [ 0.38697445],
        [ 0.82205844]], dtype=float32),
 array([0.3149658], dtype=float32)]

In [80]:
temp_optimal_info = {
    'neurons' : temp_RBF['neurons'],
    'centers' : temp_RBF['centers'],
    'sigma' : temp_RBF['sigma'],
    'x_min' : temp_min,
    'x_max' : temp_max,
    'y_min' : temp_y_scaler.data_min_,
    'y_max' : temp_y_scaler.data_max_,
    'ann_weights' : temp_ann.get_weights()[0],
    'ann_bias' : temp_ann.get_weights()[1]
}

jbl.dump(temp_optimal_info, 'models/temp_optimal_info.jbl')

['models/temp_optimal_info.jbl']

In [149]:
humidity_optimal_info = {
    'neurons' : humidity_RBF['neurons'],
    'centers' : humidity_RBF['centers'],
    'sigma' : humidity_RBF['sigma'],
    'x_min' : humidity_x_scaler.data_min_,
    'x_max' : humidity_x_scaler.data_max_,
    'y_min' : humidity_y_scaler.data_min_,
    'y_max' : humidity_y_scaler.data_max_,
    'ann_weights' : humidity_ann.get_weights()[0],
    'ann_bias' : humidity_ann.get_weights()[1]
}

jbl.dump(humidity_optimal_info, 'models/humidity_optimal_info.jbl')

['models/humidity_optimal_info.jbl']

In [161]:
load_optimal_info = {
    'neurons' : load_RBF['neurons'],
    'centers' : load_RBF['centers'],
    'sigma' : load_RBF['sigma'],
    'x_min' : load_x_scaler.data_min_,
    'x_max' : load_x_scaler.data_max_,
    'y_min' : load_y_scaler.data_min_,
    'y_max' : load_y_scaler.data_max_,
    'ann_weights' : load_ann.get_weights()[0],
    'ann_bias' : load_ann.get_weights()[1]
}

jbl.dump(load_optimal_info, 'models/load_optimal_info.jbl')

['models/load_optimal_info.jbl']

- inputs
- scale
- predict
- descale

In [172]:
load_X.shape

(12,)

In [175]:
load_X_scaled = scale(load_X, load_x_scaler.data_min_, load_x_scaler.data_max_)
load_X_scaled

array([[0.26745294, 0.2803994 , 0.2803994 , 0.24811643, 0.29325693,
        0.35304726, 0.26735294, 0.32399393, 0.        , 0.5       ,
        0.51724138, 0.54545455]])

In [177]:
ae_model = load_model('Autoencoder_ls_10_bs_64.h5', compile=False)
ae_out = ae_model.predict(load_X_scaled.reshape(1, -1))
ae_out.shape

1/1 [==============================] - 0s 58ms/step


2023-03-11 13:31:39.283069: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


(1, 10)

In [178]:
ae_out = pd.DataFrame(ae_out).drop(3, axis=1).to_numpy()
ae_out

array([[0.90358514, 0.2838107 , 1.7103277 , 2.8699527 , 0.4922726 ,
        0.99366343, 1.5130675 , 0.8130185 , 2.1930919 ]], dtype=float32)

In [179]:
ae_out.shape

(1, 9)

In [201]:
out_matrix(ae_out, load_RBF['neurons'], load_RBF['centers'], load_RBF['sigma'])

array([[0.62070864, 0.8128785 , 0.48164003, 0.76648517, 0.77100471,
        0.66448312, 0.57024745, 0.66642697, 0.49158494, 0.75644878,
        0.71862719, 0.62528479, 0.82985327, 0.63199787, 0.78927861,
        0.9362825 , 0.73030643, 0.47618812, 0.6451192 ]])

In [184]:
load_ann.predict(out_matrix(ae_out, load_RBF['neurons'], load_RBF['centers'], load_RBF['sigma']))

1/1 [==============================] - 0s 58ms/step


2023-03-11 13:42:22.168606: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.32964164]], dtype=float32)

In [187]:
load = (np.array([[6619.96585773]]) - np.array([458.02005145])) * 0.32964164 + np.array([458.02005145])
load

array([[2489.25397262]])

In [199]:
def scale(x, min, max):
    return np.array([[(x[i] - min[i]) / (max[i] - min[i]) for i in range(len(x))]])

def descale(x_scaled, min, max):
    return (max - min) * x_scaled + min

def out_matrix(X, n_hidden, centroids, sigma_mat):
        out_mat = np.zeros((X.shape[0], n_hidden))
        for i in range(len(X)):
            for j in range(n_hidden):
                numerator = -np.square(X[i] - centroids[j]).sum()
                denominator = 2*(np.square(sigma_mat[j]))
                out_mat[i][j] = np.exp(numerator/denominator)
        return out_mat

def autoEncoder(inputs, file_path:str):
    ae_model = tf.keras.models.load_model(file_path)
    return pd.DataFrame(ae_model.predict(inputs)).drop(3, axis=1).to_numpy()

def predict(inputs, file_path:str, ae_filepath:str=None, load=False):
    metadata = jbl.load(file_path)  
    if load: x_scaled = autoEncoder(inputs, ae_filepath)      
    else: x_scaled = scale(inputs, metadata['x_min'], metadata['x_max'])
    out_mat = out_matrix(x_scaled, metadata['neurons'], metadata['centers'], metadata['sigma'])
    print(out_mat)
    ann_out = out_mat @ metadata['ann_weights'] + metadata['ann_bias']
    return descale(ann_out, metadata['y_min'], metadata['y_max'])

In [194]:
autoEncoder(load_X_scaled, 'Autoencoder_ls_10_bs_64.h5')

1/1 [==============================] - 0s 46ms/step


2023-03-11 13:49:39.260210: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.90358514, 0.2838107 , 1.7103277 , 2.8699527 , 0.4922726 ,
        0.99366343, 1.5130675 , 0.8130185 , 2.1930919 ]], dtype=float32)

In [151]:
predict(temp_X, 'models/temp_optimal_info.jbl')

[[0.5862069  0.5862069  0.71590909 0.81818182 0.        ]]
[[0.46287085 0.61675923 0.97619411 0.3392412  0.33633413 0.96949456
  0.40489012 0.81247055 0.27885335 0.60393592 0.29958091 0.47153092]]


array([[83.45884478]])

In [152]:
predict(temp_X, 'models/humidity_optimal_info.jbl')

[[0.5862069  0.5862069  0.71590909 0.81818182 0.        ]]
[[0.29140949 0.45259908 0.22644311 0.36287695 0.96577146 0.79581475
  0.58411555 0.28863625 0.42788496 0.97266629 0.56922217 0.24680899]]


array([[82.28206776]])

In [206]:
predict(load_X_scaled, 'models/load_optimal_info.jbl', load=True, ae_filepath='Autoencoder_ls_10_bs_64.h5')

1/1 [==============================] - 0s 47ms/step
[[0.62070864 0.8128785  0.48164003 0.76648517 0.77100471 0.66448312
  0.57024745 0.66642697 0.49158494 0.75644878 0.71862719 0.62528479
  0.82985327 0.63199787 0.78927861 0.9362825  0.73030643 0.47618812
  0.6451192 ]]


2023-03-11 14:09:10.487194: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[2385.82555987]])

In [207]:
load_X_scaled.shape

(1, 12)

In [203]:
temp_X.shape

(5,)

In [204]:
load_X_scaled

array([[0.26745294, 0.2803994 , 0.2803994 , 0.24811643, 0.29325693,
        0.35304726, 0.26735294, 0.32399393, 0.        , 0.5       ,
        0.51724138, 0.54545455]])

In [205]:
load

array([[2489.25397262]])